# Generated by Django 3.0.5 on 2020-04-24 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0001_initial'),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Domaine',
                'verbose_name_plural': '   Domaines',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': '    Grades',
            },
        ),
        migrations.CreateModel(
            name='TypeEnseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TypeEnseignant',
                'verbose_name_plural': 'TypeEnseignants',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_tutor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(help_text="structure d'enseignement", max_length=50)),
                ('date_de_naissance', models.DateField(default=django.utils.timezone.now)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('contact', models.CharField(max_length=8)),
                ('piece_indentite', models.FileField(default='none.png', upload_to='tuteur/pieces/')),
                ('photo', models.FileField(default='none.png', upload_to='tuteur/photos/')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('domaine', models.ManyToManyField(related_name='competence_tuteur', to='gestion.Domaine')),
                ('localite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enseignement.Localite')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tuteur',
                'verbose_name_plural': 'Tuteurs',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20)),
                ('structure', models.CharField(help_text="structure d'enseignement", max_length=50)),
                ('date_de_naissance', models.DateField(default=django.utils.timezone.now)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('contact', models.CharField(max_length=8)),
                ('piece_indentite', models.FileField(default='none.png', upload_to='enseignant/pieces/')),
                ('photo', models.FileField(default='none.png', upload_to='enseignant/photos/')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('domaine', models.ManyToManyField(related_name='competence_enseignant', to='gestion.Domaine')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.Grade')),
                ('localite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enseignement.Localite')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.TypeEnseignant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
            },
        ),
    ]
