# Generated by Django 3.0.5 on 2020-05-11 10:23

from django.db import migrations, models
import gestion.validators


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20200424_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FileField(default='none.png', upload_to='studentphotos/', validators=[gestion.validators.validate_file_extension_for_image]),
        ),
        migrations.AlterField(
            model_name='student',
            name='piece_indentite',
            field=models.FileField(default='none.png', upload_to='student/piece', validators=[gestion.validators.validate_file_extension_for_document]),
        ),
    ]
