# Generated by Django 3.0.5 on 2020-05-11 13:09

from django.db import migrations, models
import gestion.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20200511_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='photo',
            field=models.FileField(default='none.png', upload_to='enseignant/photos/', validators=[gestion.models.validate_file_extension_for_image]),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='piece_indentite',
            field=models.FileField(default='none.png', upload_to='enseignant/pieces/', validators=[gestion.models.validate_file_extension_for_document]),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.FileField(default='none.png', upload_to='studentphotos/', validators=[gestion.models.validate_file_extension_for_image]),
        ),
        migrations.AlterField(
            model_name='student',
            name='piece_indentite',
            field=models.FileField(default='none.png', upload_to='student/piece', validators=[gestion.models.validate_file_extension_for_document]),
        ),
    ]
