# Generated by Django 3.0.5 on 2020-05-11 14:56

from django.db import migrations, models
import gestion.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_auto_20200511_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuteur',
            name='photo',
            field=models.FileField(default='none.png', upload_to='tuteur/photos/', validators=[gestion.models.validate_file_extension_for_image]),
        ),
        migrations.AlterField(
            model_name='tuteur',
            name='piece_indentite',
            field=models.FileField(default='none.png', upload_to='tuteur/pieces/', validators=[gestion.models.validate_file_extension_for_document]),
        ),
    ]
