# Generated by Django 3.0.5 on 2020-04-26 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0004_auto_20200424_1112'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enseignement', '0007_auto_20200426_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierRecrutement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('date_de_naissance', models.DateField(help_text='Date de naissance')),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=8)),
                ('photo', models.FileField(default='none.png', upload_to='recrutement/photos/')),
                ('piece_indentite', models.FileField(default='none.png', upload_to='recrutement/pieces/')),
                ('lettre_motivation', models.FileField(default='none.png', upload_to='recrutement/lettres/')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('domaine', models.ManyToManyField(related_name='competence_candidat', to='gestion.Domaine')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Grade')),
                ('localite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.Localite')),
            ],
            options={
                'verbose_name': 'DossierRecrutement',
                'verbose_name_plural': 'DossierRecrutements',
            },
        ),
        migrations.CreateModel(
            name='Recrutement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=30)),
                ('objet', tinymce.models.HTMLField(verbose_name='objet du recrutement')),
                ('ouverture', models.DateTimeField(help_text="Date d'ouverture")),
                ('fermetture', models.DateTimeField(help_text='Date de fermeture')),
                ('cible', tinymce.models.HTMLField(verbose_name='public cible')),
                ('methode_evaluation', tinymce.models.HTMLField(verbose_name="methode d'evaluation")),
                ('date_debut_passage', models.DateTimeField(help_text='Debut des passages devant le jury')),
                ('date_fin_passage', models.DateTimeField(help_text='Fin des passages devant le jury')),
                ('resultat', models.DateTimeField(help_text='Date de publication des resultats')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recrutement',
                'verbose_name_plural': '  Recrutements',
            },
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critere1', models.IntegerField()),
                ('critere2', models.IntegerField()),
                ('critere3', models.IntegerField()),
                ('critere4', models.IntegerField()),
                ('critere5', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutement.DossierRecrutement')),
                ('juge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resultat',
                'verbose_name_plural': 'Resultats',
            },
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('membre', models.ManyToManyField(related_name='membrejury', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jury',
                'verbose_name_plural': 'Jurys',
            },
        ),
        migrations.AddField(
            model_name='dossierrecrutement',
            name='recrutement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutement.Recrutement'),
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('document', models.FileField(default='none.png', upload_to='recrutement/diplomes/% Y/% m/% d/')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplome', to='recrutement.DossierRecrutement')),
            ],
            options={
                'verbose_name': 'Diplome',
                'verbose_name_plural': 'Diplomes',
            },
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('fichier', models.FileField(default='none.png', upload_to='recrutement/certificats/% Y/% m/% d/')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificat', to='recrutement.DossierRecrutement')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
            },
        ),
    ]
