# Generated by Django 3.0.5 on 2020-04-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recrutement',
            old_name='fermetture',
            new_name='fermeture',
        ),
    ]
