# Generated by Django 3.0.5 on 2020-05-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificat',
            name='fichier',
            field=models.FileField(default='none.png', upload_to='recrutement/certificats/'),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='document',
            field=models.FileField(default='none.png', upload_to='recrutement/diplomes/'),
        ),
    ]
