# Generated by Django 3.0.5 on 2020-04-26 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20200424_1112'),
        ('recrutement', '0002_auto_20200426_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jury',
            name='membre',
            field=models.ManyToManyField(related_name='membrejury', to='gestion.Enseignant'),
        ),
        migrations.AlterField(
            model_name='resultat',
            name='juge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Enseignant'),
        ),
    ]
