# Generated by Django 3.0.5 on 2020-05-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0002_auto_20200508_0907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultat',
            options={'ordering': ('dossier',), 'verbose_name': 'Resultat', 'verbose_name_plural': 'Resultats'},
        ),
    ]
