# Generated by Django 3.0.5 on 2020-05-10 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0003_auto_20200510_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jury',
            name='nom',
        ),
        migrations.AddField(
            model_name='jury',
            name='recrutement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='recrutement.Recrutement'),
            preserve_default=False,
        ),
    ]
