# Generated by Django 3.0.5 on 2020-05-11 14:56

from django.db import migrations, models
import gestion.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0004_auto_20200510_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificat',
            name='fichier',
            field=models.FileField(default='none.png', upload_to='recrutement/certificats/', validators=[gestion.validators.validate_file_extension_for_document]),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='document',
            field=models.FileField(default='none.png', upload_to='recrutement/diplomes/', validators=[gestion.validators.validate_file_extension_for_document]),
        ),
        migrations.AlterField(
            model_name='dossierrecrutement',
            name='lettre_motivation',
            field=models.FileField(default='none.png', upload_to='recrutement/lettres/', validators=[gestion.validators.validate_file_extension_for_document]),
        ),
        migrations.AlterField(
            model_name='dossierrecrutement',
            name='photo',
            field=models.FileField(default='none.png', upload_to='recrutement/photos/', validators=[gestion.validators.validate_file_extension_for_image]),
        ),
        migrations.AlterField(
            model_name='dossierrecrutement',
            name='piece_indentite',
            field=models.FileField(default='none.png', upload_to='recrutement/pieces/', validators=[gestion.validators.validate_file_extension_for_document]),
        ),
    ]
