# Generated by Django 3.0.5 on 2020-04-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0004_jury_dossier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificat',
            old_name='nom',
            new_name='nom_certificat',
        ),
        migrations.RenameField(
            model_name='diplome',
            old_name='nom',
            new_name='nom_diplome',
        ),
    ]
