# Generated by Django 3.0.5 on 2020-05-19 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0005_auto_20200511_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dossierrecrutement',
            options={'ordering': ['-created'], 'verbose_name': 'DossierRecrutement', 'verbose_name_plural': 'DossierRecrutements'},
        ),
        migrations.AlterModelOptions(
            name='recrutement',
            options={'ordering': ['-created'], 'verbose_name': 'Recrutement', 'verbose_name_plural': '  Recrutements'},
        ),
        migrations.AlterModelOptions(
            name='resultat',
            options={'verbose_name': 'Resultat', 'verbose_name_plural': 'Resultats'},
        ),
        migrations.AlterField(
            model_name='jury',
            name='recrutement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recrutement.Recrutement'),
        ),
    ]
