# Generated by Django 3.0.5 on 2020-05-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0006_auto_20200519_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jury',
            name='dossier',
        ),
    ]
