# Generated by Django 3.0.5 on 2020-04-24 09:21

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DominaceUfr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Exemple: Mathematique/Physique/Literaire', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DominaceUfr',
                'verbose_name_plural': '          DominaceUfrs',
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom de l'etablissement", max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('directeur_general', models.CharField(help_text='nom et prenom du Directeur General', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact', models.CharField(max_length=8)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Etablissement',
                'verbose_name_plural': '           Etablissements',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Filiere',
                'verbose_name_plural': '        Filieres',
            },
        ),
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Localite',
                'verbose_name_plural': '              Localites',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Exemple: Licence/Master...', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': '      Niveaux',
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Exemple: Semestre 1', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': '     Semestres',
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.Filiere')),
            ],
            options={
                'verbose_name': 'Specialite',
                'verbose_name_plural': '       Specialites',
            },
        ),
        migrations.CreateModel(
            name='StatutEtablissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Exemple: Public /Prive', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'StatutEtablissement',
                'verbose_name_plural': '            StatutEtablissements',
            },
        ),
        migrations.CreateModel(
            name='TypeEtablissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Exemple: Universite / Grande Ecole', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TypeEtablissement',
                'verbose_name_plural': '             TypeEtablissements',
            },
        ),
        migrations.CreateModel(
            name='TypeUe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Exemple: Conaaissance Fondementale/Culture Generale', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'TypeUe',
                'verbose_name_plural': '    TypeUes',
            },
        ),
        migrations.CreateModel(
            name='UniteEnseignement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('objectif_general', tinymce.models.HTMLField(verbose_name='objectif_general')),
                ('objectif_specifique', tinymce.models.HTMLField(verbose_name='objectif specifique')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.Niveau')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.Semestre')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.Specialite')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.TypeUe')),
            ],
            options={
                'verbose_name': 'UniteEnseignement',
                'verbose_name_plural': '   UniteEnseignements',
            },
        ),
        migrations.CreateModel(
            name='Ufr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('situation', tinymce.models.HTMLField(verbose_name='situation Geographique')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('dominace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.DominaceUfr')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.Etablissement')),
            ],
            options={
                'verbose_name': 'Ufr',
                'verbose_name_plural': '         Ufrs',
            },
        ),
        migrations.AddField(
            model_name='filiere',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.Ufr'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='localite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.Localite'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='statut_etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.StatutEtablissement'),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='type_etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.TypeEtablissement'),
        ),
    ]
