# Generated by Django 3.0.5 on 2020-04-25 14:43

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_auto_20200424_1112'),
        ('enseignement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=50)),
                ('image', models.ImageField(default='none.png', upload_to='enseignement/cours')),
                ('prerequis', tinymce.models.HTMLField(verbose_name='Pre_requis')),
                ('competence', tinymce.models.HTMLField(verbose_name='Competences visées')),
                ('consigne', tinymce.models.HTMLField(verbose_name='Cnsigne')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='RessourceVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressourcevideo', to='enseignement.Cours')),
            ],
            options={
                'verbose_name': 'RessourceVideo',
                'verbose_name_plural': ',',
            },
        ),
        migrations.CreateModel(
            name='RessourcePdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(default='none.png', upload_to='cours/pdf/% Y/% m/% d/')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressourcepdf', to='enseignement.Cours')),
            ],
            options={
                'verbose_name': 'RessourcePdf',
                'verbose_name_plural': 'RessourcePdfs',
            },
        ),
        migrations.CreateModel(
            name='Ecue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=50)),
                ('image', models.ImageField(default='none.png', upload_to='enseignement/ecue')),
                ('objectif_general', tinymce.models.HTMLField(verbose_name='objectif_general')),
                ('objectif_specifique', tinymce.models.HTMLField(verbose_name='objectif specifique')),
                ('competence', tinymce.models.HTMLField(verbose_name='Competences visées')),
                ('materiel', tinymce.models.HTMLField(verbose_name='Materiel pédagogique')),
                ('temp_cours_magistral', models.IntegerField()),
                ('temps_travaux_dirige', models.IntegerField()),
                ('temps_travaux_pratique', models.IntegerField()),
                ('credit', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecue_enseignant', to='gestion.Enseignant')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.UniteEnseignement')),
            ],
            options={
                'verbose_name': 'Ecue',
                'verbose_name_plural': ' Ecue',
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='ecue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enseignement.Ecue'),
        ),
    ]
