# Generated by Django 3.0.5 on 2020-04-25 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0003_auto_20200425_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialite',
            name='filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialite_filiere', to='enseignement.Filiere'),
        ),
    ]
