# Generated by Django 3.0.5 on 2020-04-25 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0004_auto_20200425_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecue',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecue_ue', to='enseignement.UniteEnseignement'),
        ),
    ]
