# Generated by Django 3.0.5 on 2020-04-25 15:56

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0005_auto_20200425_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='consigne',
            field=tinymce.models.HTMLField(verbose_name='Consigne'),
        ),
    ]
