# Generated by Django 3.0.5 on 2020-04-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0006_auto_20200425_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='ressourcepdf',
            name='nom',
            field=models.CharField(default='UN NOM COMME CA', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ressourcevideo',
            name='nom',
            field=models.CharField(default='UN NON', max_length=50),
            preserve_default=False,
        ),
    ]
