# Generated by Django 3.0.5 on 2020-05-11 14:56

from django.db import migrations, models
import django.db.models.deletion
import gestion.validators


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0007_auto_20200426_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='image',
            field=models.ImageField(default='none.png', upload_to='enseignement/cours', validators=[gestion.validators.validate_file_extension_for_image]),
        ),
        migrations.AlterField(
            model_name='ressourcepdf',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ressourcepdf', to='enseignement.Cours', validators=[gestion.validators.validate_file_extension_for_document]),
        ),
    ]
