# Generated by Django 3.0.5 on 2020-05-19 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0009_auto_20200512_1658'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cours',
            options={'ordering': ['-created'], 'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='ecue',
            options={'ordering': ['-created'], 'verbose_name': 'Ecue', 'verbose_name_plural': ' Ecue'},
        ),
    ]
