# Generated by Django 3.0.6 on 2020-05-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0010_auto_20200519_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='sigle',
            field=models.CharField(default='UFHB', help_text='Exemple: UFHB', max_length=10),
            preserve_default=False,
        ),
    ]
