# Generated by Django 3.0.6 on 2020-05-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0011_etablissement_sigle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='nom',
            field=models.CharField(help_text="Nom de l'etablissement", max_length=100),
        ),
    ]
