# Generated by Django 3.0.6 on 2020-05-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0012_auto_20200531_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='site',
            field=models.CharField(default='http://www.univ-fhb.edu.ci', max_length=100),
            preserve_default=False,
        ),
    ]
