# Generated by Django 3.0.6 on 2020-05-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0013_etablissement_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='ufr',
            name='sigle',
            field=models.CharField(default='nan', max_length=50),
            preserve_default=False,
        ),
    ]
