# Generated by Django 3.0.6 on 2020-05-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0014_ufr_sigle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ufr',
            name='directeur',
            field=models.CharField(default='pap', help_text="nom et prenom du Directeur de l'ufr", max_length=50),
            preserve_default=False,
        ),
    ]
