# Generated by Django 3.0.6 on 2020-05-31 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0015_ufr_directeur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ufr',
            name='situation',
        ),
    ]
