# Generated by Django 3.0.6 on 2020-06-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0016_remove_ufr_situation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ufr',
            name='directeur',
        ),
        migrations.AddField(
            model_name='ufr',
            name='doyen',
            field=models.CharField(default='neant', help_text="nom et prenom du doyen de l'ufr", max_length=50),
            preserve_default=False,
        ),
    ]
