# Generated by Django 3.0.6 on 2020-06-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0017_auto_20200601_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufr',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
