# Generated by Django 3.0.6 on 2020-06-01 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0018_auto_20200601_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ufr_filiere', to='enseignement.Ufr'),
        ),
    ]
