# Generated by Django 3.0.6 on 2020-06-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignement', '0019_auto_20200601_1552'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ufr',
            options={'verbose_name': 'Ufr', 'verbose_name_plural': '         Ufr'},
        ),
    ]
